["Rayhan Ramdhany Hanaputra"]
[["Rayhan Ramdhany Hanaputra".cert]]
title = "Certified eXpert Mobile Application Pentester"
url = "https://github.com/TCP1P/Hall-Of-Fame/tree/main/2024/Certificate/889a692fddc8955d6d3145be8e4e81b483989581bf1e75dfc2f193e8b4a4332f.pdf"

["Emir Shamsuddin Fadhlurrahman"]
[["Emir Shamsuddin Fadhlurrahman".cert]]
title = "Certified XSS Vulnerability Pentester"
url = "https://github.com/TCP1P/Hall-Of-Fame/tree/main/2024/Certificate/df4054bd5730b0b5ed5d502f12e6fc8f09615e0e442686dcdd9855d5da2b2c0b.pdf"

["Ardhi Putra Pradana"]
[["Ardhi Putra Pradana".cert]]
title = "Certified XSS Vulnerability Pentester"
url = "https://github.com/TCP1P/Hall-Of-Fame/tree/main/2024/Certificate/89b59d61574fa863bc64f09a153e2e460aad3c6f8130dae498212b7aa7ba258e.pdf"

["Moch. Sofyan Firdaus"]
[["Moch. Sofyan Firdaus".cert]]
title = "Certified Binary Vulnerability Pentester"
url = "https://github.com/TCP1P/Hall-Of-Fame/tree/main/2024/Certificate/8badcecc8eabb82fce0ee97fc6c05eb9fd99f5de2d9cea121a793a0981ee7edc.pdf"

["Azka Ainul Ma'arij"]
[["Azka Ainul Ma'arij".cert]]
title = "Certified eXpert Mobile Application Pentester"
url = "https://github.com/TCP1P/Hall-Of-Fame/tree/main/2024/Certificate/75030782abc91371b79646248349c2b73708fa42dcf746d3d9fcb527ee025db6.pdf"

